# Generated by Django 5.2.17 on 2026-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticsevent',
            old_name='payload',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='project',
            field=models.CharField(blank=True, help_text='Project slug if applicable', max_length=100, null=True),
        ),
    ]
