# Generated by Django 5.1.15 on 2026-09-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='Completed', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('project_path', models.CharField(help_text='Terminal style path e.g. ~/projects/pg-management-system', max_length=200)),
                ('tagline', models.TextField()),
                ('tech_stack', models.JSONField(default=list, help_text='List of technology names')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('case_study_problem', models.TextField(blank=True, null=True)),
                ('case_study_role', models.TextField(blank=True, null=True)),
                ('case_study_architecture', models.TextField(blank=True, null=True)),
                ('case_study_outcome', models.TextField(blank=True, null=True)),
                ('case_study_git_log', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Languages', 'Languages'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Workflow', 'Workflow')], max_length=50)),
                ('description', models.TextField()),
                ('usage_meta', models.CharField(help_text='e.g. 2 projects, intern + projects', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'name'],
            },
        ),
    ]
