# Generated by Django 5.2.17 on 2026-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_data',
            field=models.JSONField(blank=True, default=dict, help_text='Cached stats from GitHub'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='preview_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='preview_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('repository', 'Repository Screenshot'), ('readme', 'README Image'), ('github', 'GitHub Social Preview'), ('fallback', 'Design Fallback')], default='fallback', max_length=20),
        ),
    ]
